# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20160511_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(choices=[('Add', 'add'), ('Del', 'del')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='work',
            name='img',
            field=models.ImageField(upload_to='recipe'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Work'),
        ),
    ]
