# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20160513_2126'),
        ('recipe', '0004_auto_20160513_1903'),
    ]

    operations = [
    ]
