# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_remove_workcomments_deleted'),
        ('recipe', '0007_auto_20160531_1341'),
    ]

    operations = [
    ]
