# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecomments',
            name='deleted',
        ),
    ]
